test SafeCallback
Uniswap/v4-periphery pull request #220
Opened 2024-07-27 21:06 UTC by saucepoint

## Related Issue
Closes #183 

## Description of changes

Added a mock contract and tested that `SafeCallback.unlockCallback()` is only accessible from PoolManager

2024-07-27 21:07 UTC, saucepoint commented on test/SafeCallback.t.sol
> +        vm.stopPrank();
this is pretty neat from foundry, when fuzzing for addresses the fuzzer includes deployed contracts from setup! 😲

2024-07-31 17:50 UTC, snreynolds requested changes

2024-07-31 17:50 UTC, snreynolds commented on test/SafeCallback.t.sol
> +    function test_unlock(uint256 num) public {
can we also just add an assert that the pool manager in SafeCallback is the address we expect/the pool manager address we initialized it with

2024-07-31 18:15 UTC, snreynolds approved these changes

2024-07-31 18:16 UTC, merged